backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from duomath import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('user/', include('users.urls')),
    path('course/', include('courses.urls')),
    path('admin/', admin.site.urls),
]

backend/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns=[
    path('', views.show_courses, name='index'),
    path('add=<int:course_pk><str:name>', views.add_new_course, name='add_new_course'),
    path('show_all_courses/', views.show_all_courses, name='show_all_courses'),
    path('course=<int:user_course_pk><str:name>/', views.show_chapters, name='show_chapters'),
    path('chapter=<int:user_chapter_pk><str:name>/', views.show_lessons, name='show_lessons'),
    path('lesson=<int:user_lesson_pk><str:name>/', views.do_lesson, name='do_lesson'),
]

backend/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns=[
    path('', views.user, name='user'),
    path('register/', views.register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]

backend/courses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.


class DuoMathCourse(models.Model):

    class SchoolType(models.TextChoices):
        PRIMARY_SCHOOL = "PS", _('Primary School')
        SECONDARY_SCHOOL = "SS", _('Secondary School')

    class LevelType(models.TextChoices):
        BASIC = "B", _('Basic')
        ADVANCE = "A", _('Advance')

    course_name = models.CharField(max_length=100, default="Course name")
    type_of_school = models.CharField(max_length=2, choices=SchoolType.choices, default=SchoolType.PRIMARY_SCHOOL)
    type_of_level = models.CharField(max_length=1, choices=LevelType.choices, default=LevelType.BASIC)

    def __str__(self):
        return f"{self.id} - {self.type_of_school} - {self.type_of_level}"


class Chapter(models.Model):
    chapter_name = models.CharField(max_length=50, default="Chapter name")
    chapter_number = models.PositiveIntegerField(default=0)
    course = models.ForeignKey(DuoMathCourse, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} - {self.chapter_name}"


class Lesson(models.Model):
    lesson_topic = models.CharField(max_length=50, default="Lesson topic")
    lesson_number = models.PositiveIntegerField(default=0)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.id} - {self.lesson_topic}"


class Exercise(models.Model):

    class ExerciseDifficult(models.TextChoices):
        EASY = "E", _("Easy")
        MID = "M", _("Mid")
        HARD = "H", _("Hard")

    exercise_number = models.PositiveIntegerField(default=0)
    function_name = models.CharField(max_length=13, default="PPPCH00L00E00")
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True)
    difficult = models.CharField(max_length=1, choices=ExerciseDifficult.choices, default=ExerciseDifficult.EASY)
    text = models.CharField(max_length=300, default="Text")
    answear = models.CharField(max_length=300, default="Answear")
    points = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.id} - {self.function_name} - {self.points}"

backend/courses/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import DuoMathCourse
from users.models import DuoMathUser, UserCourse, UserChapter, UserLesson, UserExercise
# Create your views here.

def show_courses(request):
    if request.user.is_authenticated:
        user_courses = UserCourse.objects.filter(user=request.user)
        return render(request, 'courses/index.html', {'courses': user_courses})
    else:
        return render(request, 'users/login.html')
    return render(request, 'duomath/index.html')

def show_chapters(request, name, user_course_pk):
    if request.user.is_authenticated:
        user_course = UserCourse.objects.get(pk=user_course_pk)
        user_chapters = UserChapter.objects.filter(user_course=user_course)
        return render(request, 'courses/index.html', {'chapters': user_chapters})
    else:
        return render(request, 'users/login.html')
    return render(request, 'duomath/index.html')

def show_lessons(request, name, user_chapter_pk):
    if request.user.is_authenticated:
        user_chapter = UserChapter.objects.get(pk=user_chapter_pk)
        user_lessons = UserLesson.objects.filter(user_chapter=user_chapter)
        return render(request, 'courses/index.html', {'lessons': user_lessons})
    else:
        return render(request, 'users/login.html')
    return render(request, 'duomath/index.html')

def show_all_courses(request):
    if request.user.is_authenticated:
        courses = DuoMathCourse.objects.all()
        return render(request, 'courses/index.html', {'all_courses': courses})
    return render(request, 'duomath/index.html')

def add_new_course(request, name, course_pk):
    if request.user.is_authenticated:
        user_course = UserCourse.objects.filter(user=request.user, course__pk=course_pk)
        if not user_course:

            course = DuoMathCourse.objects.get(pk=course_pk)

            new_user_course = UserCourse(user=request.user, course=course)
            new_user_course.save()

            return render(request, 'courses/index.html')
        else:
            return render(request, 'courses/index.html')
    else:
        return render(request, 'users/login.html')
    return render(request, 'duomath/index.html')


def do_lesson(request, name, user_lesson_pk):
    if request.user.is_authenticated:
        user_lesson = UserLesson.objects.get(pk=user_lesson_pk)
        user_exercises = UserExercise.objects.filter(user_lesson=user_lesson)
        print(user_lesson, user_lesson_pk)
        print(user_exercises)
        return render(request, 'courses/index.html', {'exercises': user_exercises})
    else:
        return render(request, 'users/login.html')
    return render(request, 'duomath/index.html')

backend/templates/courses/index.html
{% extends '../duomath/base.html' %}
{% block body_block %}

<div>
    <form method="POST" action="{% url 'courses:show_all_courses' %}">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ request.user.id }}">
            <button type="submit">+ Add New Course</button>
    </form>
    {% if courses %}
        {% for course in courses %}
            {% if course.completed %}
                <div style="background-color: green">
            {% else %}
                <div style="background-color: gray">
            {% endif %}
                    <a href="{% url 'courses:show_chapters' name=course.course.course_name user_course_pk=course.pk %}">
                        <div><img src="" alt="Zdjęcie"></div>
                        <div>
                            <div>{{ course.course.course_name }}</div>
                            <div>{{ course.course.get_type_of_school_display }}</div>
                            <div>{{ course.course.get_type_of_level_display }}</div>
                            <div>progress_bar</div>
                        </div>
                    </a>
                </div>
        {% endfor %}
    {% endif %}

    {% if all_courses %}
        {% for course in all_courses %}
                <div style="background-color: gray">
                    <a href="{% url 'courses:add_new_course' name=course.course_name course_pk=course.pk %}">
                        <div><img src="" alt="Zdjęcie"></div>
                        <div>
                            <div>{{ course.course_name }}</div>
                            <div>{{ course.get_type_of_school_display }}</div>
                            <div>{{ course.get_type_of_level_display }}</div>
                            <div>progress_bar</div>
                        </div>
                    </a>
                </div>
        {% endfor %}
    {% endif %}

    {% if chapters %}
        {% for chapter in chapters %}
            {% if chapter.completed %}
                <div style="background-color: green">
            {% else %}
                <div style="background-color: gray">
            {% endif %}
                    <a href="{% url 'courses:show_lessons' name=chapter.chapter.chapter_name user_chapter_pk=chapter.pk %}">
                        <div><img src="" alt="Zdjęcie"></div>
                        <div>
                            <div>{{ chapter.chapter.chapter_number }}. {{ chapter.chapter.chapter_name }}</div>
                            <div>progress_bar</div>
                        </div>
                    </a>
                </div>
        {% endfor %}
    {% endif %}

    {% if lessons %}
        {% for lesson in lessons %}
            {% if lesson.completed %}
                <div style="background-color: green">
            {% else %}
                <div style="background-color: gray">
            {% endif %}
                    <a href="{% url 'courses:do_lesson' name=lesson.lesson.lesson_topic user_lesson_pk=lesson.pk %}">
                        <div><img src="" alt="Zdjęcie"></div>
                        <div>
                            <div>{{ lesson.lesson.lesson_number }}. {{ lesson.lesson.lesson_topic }}</div>
                        </div>
                    </a>
                </div>
        {% endfor %}
    {% endif %}

    {% if exercises %}
        {% for exercise in exercises %}
            {% if not exercise.completed %}
                <div>
                    <div>{{ exercise.exercise.text }}</div>
                    <div>{{ exercise.exercise.function_name }}</div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

{% endblock %}