backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from duomath import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('user/', include('users.urls')),
    path('course/', include('courses.urls')),
    path('admin/', admin.site.urls),
]

backend/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns=[
    path('', views.show_courses, name='index'),
    path('add=<int:course_pk><str:name>', views.add_new_course, name='add_new_course'),
    path('show_all_courses/', views.show_all_courses, name='show_all_courses'),
    path('course=<int:user_course_pk><str:name>/', views.show_chapters, name='show_chapters'),
    path('chapter=<int:user_chapter_pk><str:name>/', views.show_lessons, name='show_lessons'),
    path('lesson=<int:user_lesson_pk><str:name>/', views.do_lesson, name='do_lesson'),
]

backend/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns=[
    path('', views.user, name='user'),
    path('register/', views.register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]

backend/duomath/models.py
from django.db import models

# Create your models here.

backend/duomath/views.py
from django.shortcuts import render
# Create your views here.


def index(request):
    return render(request, 'duomath/index.html')

def about_us(request):
    return render(request, 'duomath/about_us.html')

backend/templates/duomath/about_us.html
{% extends 'duomath/base.html' %}
{% block body_block %}

<div>
    <h1>About us</h1>
</div>

{% endblock %}

backend/templates/duomath/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <nav>
            <div>
                <ul>
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'about_us' %}">About_us</a></li>

                    {% if user.is_authenticated %}
                        <li><a  href="{% url 'users:user' %}">User</a></li>
                        <li><a  href="{% url 'courses:index' %}">Course</a></li>
                        <li><a  href="{% url 'users:user_logout' %}">Logout</a></li>
                    </ul>
                    <div>
                        Picture {{ user.username }}
                    </div>
                    {% else %}
                        <li><a  href="{% url 'users:user_register' %}">Register</a></li>
                        <li><a  href="{% url 'users:user_login' %}">Login</a></li>
                    </ul>
                    {% endif %}

            </div>
        </nav>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <footer>
            Footer
        </footer>
    </body>
</html>

backend/templates/duomath/index.html
{% extends 'duomath/base.html' %}
{% block body_block %}

<div>
    <h1>DuoMath</h1>
</div>

{% endblock %}